### ISSUE TITLE
WiFi Password Recovery 2.0 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/WiFi-Password-Recovery#1]
- [x] Fix program loading bug on Windows XP SP3
- [x] Fix a bug on recovering passwords on Windows Vista
- [ ] Show proper error message when running WiFi Password Recovery on unsupported Windows versions
- [x] Add welcome dialog
- [x] Improve password text box UI
- [x] Improve *About WiFi Password Recovery* window UI
- [x] Improve main window UI
- [x] Implement multi-language support
- [x] Export wireless network data to file *(Windows and macOS only)*
- [x] Implement encryption on exported files
- [ ] macOS version (work-in-progress)
- [ ] Android version (work-in-progress)

*Contributions are welcome for a Linux port of WiFi Password Recovery*
